# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'infoMarco' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Kingfisher'

end
