# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

  use_frameworks!

  # Pods for infoMarco

  target 'infoMarco' do

   
   pod 'Firebase/Auth'
   pod 'Firebase/Database'
   pod 'Firebase/Firestore'
   pod 'Firebase', '>= 2.5.1'
   pod 'Firebase/InAppMessaging'

  end



